# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Primeira Actiom básica

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Fiap-Git-Actions/Fiap-Git-Actions/slnGitHubActions/API/API.csproj
    - name: Build
      run: dotnet build --no-restore ./Fiap-Git-Actions/Fiap-Git-Actions/slnGitHubActions/API/API.csproj
